development:
  database_url: "https://do-an-c9a0a-default-rtdb.firebaseio.com/"
  secret_key: "FIqeWxFansbjJcVOXHRTAUHUunamkMyMT7Y5Dxan"

production:
  database_url: "https://do-an-c9a0a-default-rtdb.firebaseio.com/"
  secret_key: "FIqeWxFansbjJcVOXHRTAUHUunamkMyMT7Y5Dxan"